// Autogenerated from Pigeon (v3.2.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class VideoItem;

@interface VideoItem : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithVideoUrl:(NSString *)videoUrl
    size:(NSNumber *)size;
@property(nonatomic, copy) NSString * videoUrl;
@property(nonatomic, strong) NSNumber * size;
@end

/// The codec used by VideoPlayerHelperApi.
NSObject<FlutterMessageCodec> *VideoPlayerHelperApiGetCodec(void);

@protocol VideoPlayerHelperApi
- (void)precacheVideosVideos:(NSArray<VideoItem *> *)videos completion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)precacheVideoVideo:(VideoItem *)video completion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)preparePlayerAfterErrorTextureId:(NSNumber *)textureId error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void VideoPlayerHelperApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<VideoPlayerHelperApi> *_Nullable api);

NS_ASSUME_NONNULL_END
