// Autogenerated from Pigeon (v3.2.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "MessagesHelper.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface VideoItem ()
+ (VideoItem *)fromMap:(NSDictionary *)dict;
+ (nullable VideoItem *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation VideoItem
+ (instancetype)makeWithVideoUrl:(NSString *)videoUrl
    size:(NSNumber *)size {
  VideoItem* pigeonResult = [[VideoItem alloc] init];
  pigeonResult.videoUrl = videoUrl;
  pigeonResult.size = size;
  return pigeonResult;
}
+ (VideoItem *)fromMap:(NSDictionary *)dict {
  VideoItem *pigeonResult = [[VideoItem alloc] init];
  pigeonResult.videoUrl = GetNullableObject(dict, @"videoUrl");
  NSAssert(pigeonResult.videoUrl != nil, @"");
  pigeonResult.size = GetNullableObject(dict, @"size");
  NSAssert(pigeonResult.size != nil, @"");
  return pigeonResult;
}
+ (nullable VideoItem *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [VideoItem fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"videoUrl" : (self.videoUrl ?: [NSNull null]),
    @"size" : (self.size ?: [NSNull null]),
  };
}
@end

@interface VideoPlayerHelperApiCodecReader : FlutterStandardReader
@end
@implementation VideoPlayerHelperApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [VideoItem fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface VideoPlayerHelperApiCodecWriter : FlutterStandardWriter
@end
@implementation VideoPlayerHelperApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[VideoItem class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface VideoPlayerHelperApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation VideoPlayerHelperApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[VideoPlayerHelperApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[VideoPlayerHelperApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *VideoPlayerHelperApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    VideoPlayerHelperApiCodecReaderWriter *readerWriter = [[VideoPlayerHelperApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void VideoPlayerHelperApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<VideoPlayerHelperApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.VideoPlayerHelperApi.precacheVideos"
        binaryMessenger:binaryMessenger
        codec:VideoPlayerHelperApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(precacheVideosVideos:completion:)], @"VideoPlayerHelperApi api (%@) doesn't respond to @selector(precacheVideosVideos:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSArray<VideoItem *> *arg_videos = GetNullableObjectAtIndex(args, 0);
        [api precacheVideosVideos:arg_videos completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.VideoPlayerHelperApi.precacheVideo"
        binaryMessenger:binaryMessenger
        codec:VideoPlayerHelperApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(precacheVideoVideo:completion:)], @"VideoPlayerHelperApi api (%@) doesn't respond to @selector(precacheVideoVideo:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        VideoItem *arg_video = GetNullableObjectAtIndex(args, 0);
        [api precacheVideoVideo:arg_video completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.VideoPlayerHelperApi.preparePlayerAfterError"
        binaryMessenger:binaryMessenger
        codec:VideoPlayerHelperApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(preparePlayerAfterErrorTextureId:error:)], @"VideoPlayerHelperApi api (%@) doesn't respond to @selector(preparePlayerAfterErrorTextureId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_textureId = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api preparePlayerAfterErrorTextureId:arg_textureId error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
