// Autogenerated from Pigeon (v3.2.9), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by VideoPlayerHelperApi.
NSObject<FlutterMessageCodec> *VideoPlayerHelperApiGetCodec(void);

@protocol VideoPlayerHelperApi
- (void)precacheVideosVideos:(NSArray<NSString *> *)videos completion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)precacheVideoVideoUrl:(NSString *)videoUrl completion:(void(^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void VideoPlayerHelperApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<VideoPlayerHelperApi> *_Nullable api);

NS_ASSUME_NONNULL_END
